sudo: false
language: node_js
node_js:
  - "4.0"
  - "5.0"

before_install:
  - "npm install -g codeclimate-test-reporter istanbul"

addons:
  code_climate:
    repo_token: d20610ac787537aa70c7a5cf16e2c8acefed2e67bc22fe7b78ce49ce5bf9c96b

script:
  - "npm run cover"

after_script:
  - "cat ./coverage/lcov.info | codeclimate-test-reporter"
